<!DOCTYPE html>
<html lang="en">
<head>
  <title>Bootstrap Example</title>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
  <script src="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js"></script>
</head>
<body>
<div class="container" style="width:50%">
  <h2>Sign Up</h2>
  <form role="form">
  	<div class="form-group">
      <label for="name">First Name:</label>
      <input type="text" class="form-control" id="name" placeholder="Enter First Name">
    </div>

    <div class="form-group">
      <label for="email">Email:</label>
      <input type="email" class="form-control" id="email" placeholder="Enter email">
    </div>
    <div class="form-group">
      <label for="Password">Password:</label>
      <input type="password" class="form-control" id="password" placeholder="Enter password">
    </div>
     <div class="form-group">
      <label for="Password">Confirm Password:</label>
      <input type="password" class="form-control" id="confirmpassword" placeholder="Re-enter password">
    </div>
    
    <button type="submit" class="btn btn-default">Submit</button>
  </form>
</div>
</body>
</html>